### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/Surakku#1]
# Meta

- [ ] There is no homepage! [enable here](https://github.com/NeonGamerBot-QK/Surakku)

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] if possible make your app docker compatible? (beta)

- [ ] if possible make your app docker compatible? (beta)

- [ ] This repo does not have a license

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] undefined
# Automation

- [ ] **Mark this to override & close this issue.**
